### ISSUE TITLE
FormFor always pass new onBlur, onChange, onMount,  onFocus for Input Field

### ISSUE THREAD

**Issue by iamn00b** [form-for/form-for#3]
I tried to make a form with multiple custom phone number input, which each input field contains country codes picker (using `semantic-ui-react` `Dropdown`). After adding that, the form becomes significantly slow. After a quick check, the problem is that country codes picker re-render all the list every user input. Using `PureComponent` on custom input does not help because the function props (`onBlur`, `onChange`, etc) is always passed new function. 

While the problem can simply be fixed by using `shouldComponentUpdate`, I just curious, is that necessary to pass new function every changes/render?

In case you are wondering my custom select input:
```js
// @flow

import * as React from 'react';
import { Dropdown } from 'semantic-ui-react';

// this is just red text
import ErrorLabel from '../FormForErrorLabel/FormForErrorLabel';

import type { ComponentProps } from 'form-for';

export type Props = {
  options: any,
  placeholder?: string,
  ref?: Function,
  wrapperProps: any,
  required?: boolean,
} & ComponentProps;

export default class FormForSelection extends React.Component<Props> {
  select: ?HTMLSelectElement;

  handleRef = (el: ?HTMLSelectElement) => {
    this.select = el;

    if (this.props.ref) {
      this.props.ref(el);
    }
  };

  componentDidMount() {
    if (this.props.onMount) {
      this.props.onMount(this.select);
    }
  }

  shouldComponentUpdate(nextProps: Props) {
    const importantProps = ['name', 'value', 'options'];

    return importantProps
      // $FlowFixMe
      .map(propKey => nextProps[propKey] !== this.props[propKey])
      .reduce((acc, res) => acc || res, false);
  }

  render() {
    const { type, error, onMount, wrapperProps, ...props } = { ...this.props };
    if (error) {
      props['aria-invalid'] = true;
    }

    return (
      <div {...wrapperProps}>
        <Dropdown
          {...props}
          selection
          error={Boolean(error)}
          ref={this.handleRef}
        />
        <ErrorLabel error={error} />
      </div>
    );
  }
}
```

**Comment by pedsmoreira** [comment]
That's a good point. Thanks for reporting the issue.

I believe there should be a shouldComponentUpdate on the `<Field/>` to avoid this from happening. If the `<Field>` doesn't update, neither will your custom component.

I'll update this and release a new patch in the next couple of days.
